`InMemoryDataset` improvements
ML4GW/ml4gw pull request #119
Opened 2024-05-08 12:06 UTC by EthanMarx

Close #69 for use in `Amplfi`

2024-05-08 12:49 UTC, wbenoit26 commented on ml4gw/dataloading/in_memory_dataset.py
> +                yield X, y
Could move this statement into the previous conditional, but it doesn't really matter

2024-05-08 12:50 UTC, wbenoit26 requested changes
Oh, and right, of course tests need to be changed to deal with the difference in return format

2024-05-09 13:48 UTC, EthanMarx commented
@wbenoit26 One more once over from you than should be good to go

2024-05-09 15:19 UTC, wbenoit26 approved these changes

2024-05-09 15:20 UTC, merged